CREATE TABLE supply (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    herb_id BIGINT NOT NULL,
    spec_id BIGINT,
    quantity DECIMAL(10,2),
    unit VARCHAR(20),
    price DECIMAL(10,2),
    price_type VARCHAR(20) DEFAULT 'negotiable',
    origin_area_id BIGINT,
    origin_area_name VARCHAR(200),
    images JSON,
    contact_name VARCHAR(50),
    contact_phone VARCHAR(20),
    status VARCHAR(10) DEFAULT 'pending',
    expire_at DATETIME,
    view_count INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_herb (herb_id),
    INDEX idx_status (status),
    INDEX idx_user (user_id)
);

CREATE TABLE demand (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    herb_id BIGINT NOT NULL,
    spec_id BIGINT,
    quantity DECIMAL(10,2),
    unit VARCHAR(20),
    price DECIMAL(10,2),
    price_type VARCHAR(20) DEFAULT 'negotiable',
    origin_area_id BIGINT,
    origin_area_name VARCHAR(200),
    images JSON,
    contact_name VARCHAR(50),
    contact_phone VARCHAR(20),
    status VARCHAR(10) DEFAULT 'pending',
    expire_at DATETIME,
    view_count INT DEFAULT 0,
    budget_price DECIMAL(10,2),
    origin_requirement VARCHAR(200),
    delivery_address VARCHAR(300),
    deadline DATETIME,
    quote_count INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_herb (herb_id),
    INDEX idx_status (status),
    INDEX idx_user (user_id)
);
